name: Push on commit

on: 
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@v0.0.2
      env:
        API_KEY: ${{secrets.API_KEY}}
        MESSAGE: "Hope You're Still Doing Your Work"
